// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a placeholder file. Run protoc to generate the actual code.

package user

import (
	"context"
	"google.golang.org/grpc"
)

// Placeholder types - will be replaced by actual protoc-generated code
type UserServiceClient interface {
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	GetUserByEmail(ctx context.Context, in *GetUserByEmailRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
}

type UserServiceServer interface {
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	GetUserByEmail(context.Context, *GetUserByEmailRequest) (*GetUserResponse, error)
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	mustEmbedUnimplementedUserServiceServer()
}

type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error) {
	return nil, nil
}
func (UnimplementedUserServiceServer) GetUserByEmail(context.Context, *GetUserByEmailRequest) (*GetUserResponse, error) {
	return nil, nil
}
func (UnimplementedUserServiceServer) ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error) {
	return nil, nil
}
func (UnimplementedUserServiceServer) UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error) {
	return nil, nil
}
func (UnimplementedUserServiceServer) DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error) {
	return nil, nil
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return nil
}

type GetUserRequest struct {
	Id uint32
}
type GetUserByEmailRequest struct {
	Email string
}
type ListUsersRequest struct {
	Page     int32
	PageSize int32
}
type UpdateUserRequest struct {
	Id    uint32
	Name  string
	Email string
}
type DeleteUserRequest struct {
	Id uint32
}

type GetUserResponse struct {
	User *User
}
type ListUsersResponse struct {
	Users    []*User
	Total    int32
	Page     int32
	PageSize int32
}
type UpdateUserResponse struct {
	User *User
}
type DeleteUserResponse struct {
	Success bool
	Message string
}

type User struct {
	Id        uint32
	Name      string
	Email     string
	Roles     []string
	CreatedAt string
	UpdatedAt string
}
